version: "3.9"

services:
  backend:
    build:
      context: ./back
    container_name: backend-app
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./front
    container_name: frontend-app
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: unless-stopped


