version: "3.9"

services:
  backend:
    image: ghcr.io/Alex-yar13/backend:latest
    container_name: backend-app
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    image: ghcr.io/Alex-yar13/frontend:latest
    container_name: frontend-app
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: unless-stopped
