name: Build & Push images to GHCR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      # делаем имя владельца строчными (на всякий случай)
      - name: Set owner lowercase
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      # включаем QEMU для сборки под другие архитектуры
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # настраиваем buildx (нужен для multi-arch)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # логин в GHCR
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # backend: multi-arch
      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: ./back
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/backend:latest

      # frontend: multi-arch
      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./front
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/frontend:latest
