name: Build & Push images to GHCR

on:
  push:
    branches: [ "main" ]   # собираем при каждом пуше в main
  workflow_dispatch:        # возможность запустить вручную

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write       # нужно, чтобы пушить в GHCR
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: ./back
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/backend:latest

      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./front
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/frontend:latest
