name: Build & Push images to GHCR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      # Делаем имя владельца (организация/аккаунт) строчными
      - name: Set owner lowercase
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: ./back
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/backend:latest

      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./front
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/frontend:latest
