name: Build & Push images to GHCR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v4

      - name: Set env (owner lowercase + short sha)
        run: |
          echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push backend (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ./back
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/backend:latest
            ghcr.io/${{ env.OWNER_LC }}/backend:${{ env.SHORT_SHA }}

      - name: Build & push frontend (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ./front
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/frontend:latest
            ghcr.io/${{ env.OWNER_LC }}/frontend:${{ env.SHORT_SHA }}
